name: "httpx Action"
description: "httpx is a fast and multi-purpose HTTP toolkit allows to run multiple probers using retryablehttp library."
branding:
  icon: "activity"
  color: "blue"

inputs:
  list:
    description: "List of hosts to run HTTP/S Web server probbing"
    required: true
    default: ""

  output:
    description: "File to save output result"
    required: false

  json:
    description: "Store output in JSONL(ines) format"
    required: false
    default: false

  flags:
    description: "Extra httpx CLI flags to use"
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'